### ISSUE TITLE
re-enable directory permission tests in /spec/swarm/self_test.spec.js

### ISSUE THREAD

**Issue by tristanls** [tristanls/swarm#1]
For really large directories, `findit` apparently runs out of stack space. The error is caused by `seq` dependency, and results in:

```
/opt/node/lib/node_modules/swarm/node_modules/findit/node_modules/seq/index.js:76
        f.apply(cb, context.stack);
          ^
RangeError: Maximum call stack size exceeded
    at Function.APPLY_OVERFLOW (native)
    at action (/opt/node/lib/node_modules/swarm/node_modules/findit/node_modules/seq/index.js:76:11)
    at next (/opt/node/lib/node_modules/swarm/node_modules/findit/node_modules/seq/index.js:208:17)
    at /opt/node/lib/node_modules/swarm/node_modules/findit/node_modules/seq/index.js:213:30
    at /opt/node/lib/node_modules/swarm/node_modules/findit/node_modules/seq/index.js:55:24
    at Function.<anonymous> (/opt/node/lib/node_modules/swarm/node_modules/findit/index.js:40:25)
    at Function.<anonymous> (/opt/node/lib/node_modules/swarm/node_modules/findit/node_modules/seq/index.js:210:38)
    at action (/opt/node/lib/node_modules/swarm/node_modules/findit/node_modules/seq/index.js:76:11)
    at next (/opt/node/lib/node_modules/swarm/node_modules/findit/node_modules/seq/index.js:208:17)
    at /opt/node/lib/node_modules/swarm/node_modules/findit/node_modules/seq/index.js:213:30
```

For the above reason, the file/directory permissions test for the `/opt/node` directory is commented out starting with swarm version `0.1.2`

**Comment by tristanls** [comment]
swarm is deprecated
